/* eslint-disable react/prop-types */
/* eslint-disable no-unused-vars */
import React from 'react';
import { Card, CardContent } from './ui/Card';
import { 
  BarChart, Bar, XAxis, YAxis, Tooltip as RechartsTooltip, ResponsiveContainer, CartesianGrid, Cell,
  PieChart, Pie, Legend
} from 'recharts';
import { motion } from 'framer-motion';

export function VendorMatchCharts({ data }) {
  // Prep data for Cost Savings per Lane
  const savingsData = data.map(d => ({
    name: d.lane.split(' → ')[0],
    savings: d.savings
  }));

  // Group vendor allocation
  const allocation = data.reduce((acc, current) => {
     if (!acc[current.recommendedVendor]) {
         acc[current.recommendedVendor] = 1;
     } else {
         acc[current.recommendedVendor] += 1;
     }
     return acc;
  }, {});

  const allocationData = Object.keys(allocation).map(vendor => ({
      name: vendor,
      value: allocation[vendor]
  }));

  const COLORS = ['#6366F1', '#06B6D4', '#10b981', '#f59e0b'];

  const CustomTooltipSavings = ({ active, payload, label }) => {
    if (active && payload && payload.length) {
      return (
        <div className="bg-slate-800 border border-slate-700 p-3 rounded-xl shadow-xl backdrop-blur-md opacity-90 text-sm">
          <p className="text-white font-medium mb-1">{label}</p>
          <p className="text-emerald-400 font-mono font-bold">
            ₹{payload[0].value.toLocaleString()} <span className="text-slate-400 font-sans font-normal text-xs">savings</span>
          </p>
        </div>
      );
    }
    return null;
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 w-full">
      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ delay: 0.2, duration: 0.4 }}
      >
        <Card className="h-[400px] border-white/5 bg-card/80 backdrop-blur-md shadow-xl flex flex-col">
          <div className="p-6 pb-2 border-b border-white/5">
            <h3 className="text-lg font-bold text-white tracking-wide">Lane Cost Savings</h3>
            <p className="text-xs text-slate-400">Total savings generated by AI matching.</p>
          </div>
          <CardContent className="flex-1 p-6">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={savingsData} margin={{ top: 10, right: 10, left: -20, bottom: 20 }}>
                <defs>
                  <linearGradient id="colorSavings" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#10b981" stopOpacity={0.8}/>
                    <stop offset="95%" stopColor="#10b981" stopOpacity={0.2}/>
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" stroke="#ffffff10" vertical={false} />
                <XAxis 
                  dataKey="name" 
                  stroke="#64748b" 
                  fontSize={11} 
                  tickLine={false} 
                  axisLine={false}
                  angle={-45}
                  textAnchor="end"
                />
                <YAxis 
                  stroke="#64748b" 
                  fontSize={12} 
                  tickLine={false} 
                  axisLine={false} 
                />
                <RechartsTooltip content={<CustomTooltipSavings />} cursor={{ fill: '#ffffff05' }} />
                <Bar 
                  dataKey="savings" 
                  fill="url(#colorSavings)" 
                  radius={[6, 6, 0, 0]} 
                  animationDuration={1500}
                >
                  {savingsData.map((entry, index) => (
                    <Cell key={`cell-${index}`} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>
      </motion.div>

      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ delay: 0.3, duration: 0.4 }}
      >
        <Card className="h-[400px] border-white/5 bg-card/80 backdrop-blur-md shadow-xl flex flex-col">
          <div className="p-6 pb-2 border-b border-white/5">
            <h3 className="text-lg font-bold text-white tracking-wide">Vendor Allocation Distribution</h3>
            <p className="text-xs text-slate-400">Portfolio assignment of lanes to trusted carriers.</p>
          </div>
          <CardContent className="flex-1 p-4 pb-0 flex items-center justify-center relative">
             <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={allocationData}
                    cx="50%"
                    cy="50%"
                    innerRadius={60}
                    outerRadius={100}
                    paddingAngle={5}
                    dataKey="value"
                    animationDuration={1500}
                    stroke="none"
                  >
                    {allocationData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} className="hover:opacity-80 transition-opacity cursor-pointer outline-none" />
                    ))}
                  </Pie>
                  <RechartsTooltip 
                     formatter={(value, name) => [`${value} Lanes`, name]}
                     contentStyle={{ backgroundColor: '#1e293b', border: '1px solid #334155', borderRadius: '8px' }}
                     itemStyle={{ color: '#fff' }}
                  />
                  <Legend 
                     verticalAlign="bottom" 
                     height={36} 
                     iconType="circle"
                     formatter={(value) => <span className="text-slate-300 font-medium text-sm">{value}</span>}
                  />
                </PieChart>
             </ResponsiveContainer>
             <div className="absolute top-[45%] left-1/2 -translate-x-1/2 -translate-y-1/2 text-center pointer-events-none">
                <span className="block text-3xl font-bold text-white">{data.length}</span>
                <span className="text-[10px] uppercase tracking-wider text-slate-400 font-bold">Lanes</span>
             </div>
          </CardContent>
        </Card>
      </motion.div>
    </div>
  );
}
